name: MacOS CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
            
  macos_5_15_2_build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: jurplel/install-qt-action@v2
      with:
        # Directory to install Qt
        dir: # optional
        # Version of Qt to install
        version: '5.15.2'
        # Host platform
        host: 'mac'
        # Target platform for build
        target: 'desktop'
        # Architecture for Windows/Android
        arch: # optional
        # Whether or not to install Qt dependencies on Linux
        install-deps: 'true'
        # Additional Qt modules to install
        modules: 'qtscript qtscripttools'
        # Force a Qt mirror in case the default is not working
        mirror: # optional
        # Whether or not to actually download Qt
        cached: # optional, default is false
        # Version of aqtinstall to use in case of issues
        aqtversion: # optional, default is ==0.8
        # Version of py7zr to use in case of issues
        py7zrversion: # optional, default is ==0.6
        # Any extra arguments to append to the back
        extra: # optional
    - name: Install Qt and compile
      run: |
        which qmake
        qmake -r GnuplotViewerQuick.pro
        ls -lrt
        make
        ls -lrt

        which macdeployqt
        macdeployqt GnuplotViewerQuick.app -dmg -qmldir=qml -verbose=2
        ls -lrt        

